#[[redirects]]
#  from = "/en/*"
#  to = "https://test-hsd-deploy-netlify.netlify.app/en/"
#  status = 301
#  force = true
#
#[[redirects]]
#  from = "https://test-hsd-preview-netlify.netlify.app/it/*"
#  to = "https://test-hsd-deploy-netlify.netlify.app/it/"
#  status = 301
#  force = true

[[redirects]]
  from = "/de/*"
  to = "https://test-hsd-deploy-netlify.netlify.app/it/"
  status = 301
  force = true