type contentfulProductTechnicalSheetsJsonNodeTechnicalSheet {
  key: String
  value: String
}

type contentfulProductTechnicalSheetsJsonNode implements Node {
  productCode: String
  headerLabel: String
  # technicalSheet: contentfulProductTechnicalSheetsJsonNodeTechnicalSheet
}
